python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/А" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Б" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Би" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/В" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Во" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Вы" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Г" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Д" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Дон" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Е" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ж" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/З" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Зал" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Заст" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/И" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Изу" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/І" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/К" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ки" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Кор" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Л" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/М" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Н" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Нак" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Нар" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Не" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/О" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Обц" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ор" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ото" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/П" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Перел" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Пи" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Под" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Подт" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Пок" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Поо" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Пор" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Пот" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Приг" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Про" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Прор" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Р" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Расп" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/С" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Сл" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Сп" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Т" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/У" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ф" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Х" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ц" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ч" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ш" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Щ" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ъ-Ы-Ь" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ѣ" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Э" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ю" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Я" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ѧ" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ѳ" -format:3 >> pages_in_tsd3_wordlists.txt
python $PWBPATH/pwb.py listpages -family:wikisource -links:"ТСД-словник/3/Ѵ" -format:3 >> pages_in_tsd3_wordlists.txt
