<?php
/**
 * Created by PhpStorm.
 * User: Bladislav
 * Date: 02.03.2016
 * Time: 23:28
 */
require 'my.php';
require 'vendor/autoload.php';


$t = "<a href=\"/wiki/%D0%A1%D0%BB%D1%83%D0%B6%D0%B5%D0%B1%D0%BD%D0%B0%D1%8F:%D0%A1%D1%81%D1%8B%D0%BB%D0%BA%D0%B8_%D1%81%D1%8E%D0%B4%D0%B0/%D0%9A%D0%BE%D1%80%D0%B8%D0%BD%D1%84%D1%81%D0%BA%D0%B8%D0%B9_%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%B0%D1%8F_%D0%A0%D1%83%D1%81%D1%8C\" title=\"Служебная:Ссылки сюда/Коринфский Народная Русь\">ссылающиеся на это название</a>)</small></p>
<ul class=\"mw-search-results\">
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9C%D0%B5%D0%B4%D0%BE%D0%B2%D1%8B%D0%B9_%D0%A1%D0%BF%D0%B0%D1%81\" title=\"\" data-serp-pos=\"1\">Медовый Спас</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">5-7133-0704-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич</div>
<div class=\"mw-search-result-data\">27 КБ (1734 слова) - 06:15, 29 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A0%D0%BE%D0%B4%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D1%81%D0%BA%D0%B0%D1%8F_%D1%81%D1%83%D0%B1%D0%B1%D0%BE%D1%82%D0%B0\" title=\"Родительская суббота\" data-serp-pos=\"2\">Родительская суббота</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">главнейшие <span class=\"searchmatch\">народные</span> поминки совершаются в другие дни, а именно: на Радоницу, в Троицкую субботу и в Дмитриев день.  — А. А. <span class=\"searchmatch\">Коринфский</span>. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span> — М.:</div>
<div class=\"mw-search-result-data\">22 КБ (1466 слов) - 12:09, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9A%D0%BE%D1%80%D0%B8%D0%BD%D1%84%D1%81%D0%BA%D0%B8%D0%B9,_%D0%90%D0%BF%D0%BE%D0%BB%D0%BB%D0%BE%D0%BD_%D0%90%D0%BF%D0%BE%D0%BB%D0%BB%D0%BE%D0%BD%D0%BE%D0%B2%D0%B8%D1%87\" title=\"Коринфский, Аполлон Аполлонович\" data-serp-pos=\"3\"><span class=\"searchmatch\">Коринфский</span>, Аполлон Аполлонович</a>    </div> <div class=\"searchresult\">«Правительственном вестнике» <span class=\"searchmatch\">Коринфский</span> публиковал историко-этнографические очерки, которые затем вошли в книгу «<span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>. Круглый год сказаний, поверий</div>
<div class=\"mw-search-result-data\">14 КБ (886 слов) - 18:06, 22 марта 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%92%D0%BB%D0%B0%D1%81%D1%8C%D0%B5%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Власьев день\" data-serp-pos=\"4\">Власьев день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Изд-во ВГУ, 2005. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич</div>
<div class=\"mw-search-result-data\">18 КБ (1105 слов) - 01:03, 25 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%92%D0%BE%D0%B7%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D1%8C%D0%B5%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Вознесеньев день\" data-serp-pos=\"5\">Вознесеньев день</a> <span class=\"searchalttitle\">(перенаправление с <a href=\"/wiki/%D0%92%D0%BE%D0%B7%D0%BD%D0%B5%D1%81%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_%D1%80%D1%83%D1%81%D1%81%D0%BA%D0%BE%D0%B9_%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Вознесение в русской народной традиции\">Вознесение в русской <span class=\"searchmatch\">народной</span> традиции</a>)</span>   </div> <div class=\"searchresult\">культуры, 2004. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Лозка А. Ю. Беларускі <span class=\"searchmatch\">народны</span> каляндар.&nbsp;— Мн</div>
<div class=\"mw-search-result-data\">26 КБ (1594 слова) - 20:36, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%B0%D1%8F_%D0%B3%D0%BE%D1%80%D0%BA%D0%B0_(%D0%BF%D1%80%D0%B0%D0%B7%D0%B4%D0%BD%D0%B8%D0%BA)\" title=\"Красная горка (праздник)\" data-serp-pos=\"6\">Красная горка (праздник)</a> <span class=\"searchalttitle\">(перенаправление с <a href=\"/wiki/%D0%A4%D0%BE%D0%BC%D0%B8%D0%BD%D0%BE_%D0%B2%D0%BE%D1%81%D0%BA%D1%80%D0%B5%D1%81%D0%B5%D0%BD%D1%8C%D0%B5_%D0%B2_%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Фомино воскресенье в народной традиции\">Фомино воскресенье в <span class=\"searchmatch\">народной</span> традиции</a>)</span>   </div> <div class=\"searchresult\">1880.&nbsp;— 607&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Лозка А. Ю. Беларускі <span class=\"searchmatch\">народны</span> каляндар.&nbsp;— Мн</div>
<div class=\"mw-search-result-data\">14 КБ (851 слово) - 09:53, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A1%D0%B8%D0%BB%D1%8C%D0%B2%D0%B5%D1%81%D1%82%D1%80%D0%BE%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Сильвестров день\" data-serp-pos=\"7\">Сильвестров день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995</div>
<div class=\"mw-search-result-data\">9 КБ (505 слов) - 12:14, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%AF%D0%B1%D0%BB%D0%BE%D1%87%D0%BD%D1%8B%D0%B9_%D0%A1%D0%BF%D0%B0%D1%81\" title=\"Яблочный Спас\" data-serp-pos=\"8\">Яблочный Спас</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995</div>
<div class=\"mw-search-result-data\">21 КБ (1226 слов) - 13:27, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%94%D0%B2%D0%BE%D1%80%D0%BE%D0%B2%D0%BE%D0%B9\" title=\"Дворовой\" data-serp-pos=\"9\">Дворовой</a>    </div> <div class=\"searchresult\"><span class=\"searchmatch\">Коринфский</span>, 1995  Левкиевская, 1999, с. 122 ↑ Левкиевская, 1999, с. 123 ↑ Рожнова, 1992, с. 39 ↑ Плотникова, 1999, с. 31   <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> Русь</div>
<div class=\"mw-search-result-data\">8 КБ (596 слов) - 11:28, 26 ноября 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Петров день\" data-serp-pos=\"10\">Петров день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Колесникова В. С. <span class=\"searchmatch\">Русь</span> православная. Праздники и обряды.&nbsp;— М.: Олма-пресс, 2005.&nbsp;— 606&nbsp;с.&nbsp;— ISBN 5-224-05162-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание</div>
<div class=\"mw-search-result-data\">33 КБ (2064 слова) - 06:12, 29 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B5%D0%B2%D1%81%D0%BA%D0%B0%D1%8F_%D1%81%D1%83%D0%B1%D0%B1%D0%BE%D1%82%D0%B0\" title=\"Дмитриевская суббота\" data-serp-pos=\"11\">Дмитриевская суббота</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Миклухо-Маклая АН СССР.&nbsp;— М.: Наука, 1978.&nbsp;— С.&nbsp;200–222.&nbsp;— 296&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Некрылова</div>
<div class=\"mw-search-result-data\">24 КБ (1453 слова) - 06:38, 22 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9F%D0%BE%D0%BA%D1%80%D0%BE%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Покров день\" data-serp-pos=\"12\">Покров день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Логинов К. К.&nbsp;Русский <span class=\"searchmatch\">народный</span> календарь Заонежья&nbsp;// Кижский</div>
<div class=\"mw-search-result-data\">28 КБ (1656 слов) - 21:46, 11 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%92%D0%BE%D0%B7%D0%B4%D0%B2%D0%B8%D0%B6%D0%B5%D0%BD%D1%8C%D0%B5\" title=\"Воздвиженье\" data-serp-pos=\"13\">Воздвиженье</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Колесникова В. С. <span class=\"searchmatch\">Русь</span> православная. Праздники и обряды.&nbsp;— М.: Олма-пресс, 2005.&nbsp;— 606&nbsp;с.&nbsp;— ISBN 5-224-05162-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание</div>
<div class=\"mw-search-result-data\">18 КБ (1180 слов) - 20:36, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0_%D0%97%D0%B8%D0%BC%D0%BD%D0%B8%D0%B9\" title=\"Никола Зимний\" data-serp-pos=\"14\">Никола Зимний</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Колесникова В. С. <span class=\"searchmatch\">Русь</span> православная. Праздники и обряды.&nbsp;— М.: Олма-пресс, 2005.&nbsp;— 606&nbsp;с.&nbsp;— ISBN 5-224-05162-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание</div>
<div class=\"mw-search-result-data\">35 КБ (2163 слова) - 11:49, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%93%D0%BE%D0%BB%D0%BE%D0%B2%D0%BE%D1%81%D0%B5%D0%BA\" title=\"Головосек\" data-serp-pos=\"15\">Головосек</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">выхаванне, 2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Некрылова</div>
<div class=\"mw-search-result-data\">18 КБ (1129 слов) - 20:38, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%97%D0%B8%D0%BC%D0%BD%D0%B8%D0%B9_%D1%81%D0%B2%D0%B0%D0%B4%D0%B5%D0%B1%D0%BD%D0%B8%D0%BA\" title=\"Зимний свадебник\" data-serp-pos=\"16\">Зимний свадебник</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Колесникова В. С. <span class=\"searchmatch\">Русь</span> православная. Праздники и обряды.&nbsp;— М.: Олма-пресс, 2005.&nbsp;— 606&nbsp;с.&nbsp;— ISBN 5-224-05162-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание</div>
<div class=\"mw-search-result-data\">12 КБ (631 слово) - 21:00, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%95%D0%B3%D0%BE%D1%80%D0%B8%D0%B9_%D0%9E%D1%81%D0%B5%D0%BD%D0%BD%D0%B8%D0%B9\" title=\"Егорий Осенний\" data-serp-pos=\"17\">Егорий Осенний</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Александров и др., 1999 ↑ <span class=\"searchmatch\">Коринфский</span>, 1901, с. 502 ↑ <span class=\"searchmatch\">Коринфский</span>, 1901, с. 249  Грушко, 2000, с. 65 ↑ Рыбаков, 1987, с. 728 ↑ <span class=\"searchmatch\">Коринфский</span>, 1901, с. 501   Грушко</div>
<div class=\"mw-search-result-data\">16 КБ (875 слов) - 17:26, 21 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2_%D0%BF%D0%BE%D1%81%D1%82\" title=\"Петров пост\" data-serp-pos=\"18\">Петров пост</a>    </div> <div class=\"searchresult\">Лепта, 2008.&nbsp;— С.&nbsp;293-295.&nbsp;— 400&nbsp;с.&nbsp;— ISBN 978-5-9937-0024-3. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Соловьёва</div>
<div class=\"mw-search-result-data\">9 КБ (587 слов) - 11:49, 21 октября 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%95%D0%BC%D0%B5%D0%BB%D1%8C%D1%8F%D0%BD%D1%8B_%D0%9F%D0%B5%D1%80%D0%B5%D0%B7%D0%B8%D0%BC%D0%BD%D0%B8%D0%BA%D0%B8\" title=\"Емельяны Перезимники\" data-serp-pos=\"19\">Емельяны Перезимники</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">С. Суворина, 1901.&nbsp;— Т.&nbsp;1. Всенародный меяцеслов.&nbsp;— 691&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Месяцеслов</div>
<div class=\"mw-search-result-data\">15 КБ (906 слов) - 20:59, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%81%D1%82%D0%BD%D0%B0%D1%8F_%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_%D0%B2_%D1%81%D0%BB%D0%B0%D0%B2%D1%8F%D0%BD%D1%81%D0%BA%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Страстная неделя в славянской традиции\" data-serp-pos=\"20\">Страстная неделя в славянской традиции</a> <span class=\"searchalttitle\">(перенаправление с <a href=\"/wiki/%D0%A1%D1%82%D1%80%D0%B0%D1%81%D1%82%D0%BD%D0%B0%D1%8F_%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_%D0%B2_%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Страстная неделя в народной традиции\">Страстная неделя в <span class=\"searchmatch\">народной</span> традиции</a>)</span>   </div> <div class=\"searchresult\">985-01-0477-5. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич</div>
<div class=\"mw-search-result-data\">35 КБ (2094 слова) - 23:21, 6 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9E%D0%B1%D0%B6%D0%B8%D0%BD%D0%BA%D0%B8\" title=\"Обжинки\" data-serp-pos=\"21\">Обжинки</a> <span class=\"searchalttitle\">(перенаправление с <a href=\"/wiki/%D0%A3%D1%81%D0%BF%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Успение в народной традиции\">Успение в <span class=\"searchmatch\">народной</span> традиции</a>)</span>   </div> <div class=\"searchresult\">Колесникова В. С. <span class=\"searchmatch\">Русь</span> православная. Праздники и обряды.&nbsp;— М.: Олма-пресс, 2005.&nbsp;— 606&nbsp;с.&nbsp;— ISBN 5-224-05162-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск:</div>
<div class=\"mw-search-result-data\">36 КБ (2253 слова) - 21:44, 11 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9E%D1%81%D0%B5%D0%BD%D0%B8%D0%BD%D1%8B\" title=\"Осенины\" data-serp-pos=\"22\">Осенины</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Логинов К. К.&nbsp;Русский <span class=\"searchmatch\">народный</span> календарь Заонежья&nbsp;// Кижский</div>
<div class=\"mw-search-result-data\">24 КБ (1445 слов) - 21:44, 11 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A1%D0%B2%D0%B5%D1%82%D0%BB%D0%B0%D1%8F_%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_%D0%B2_%D1%81%D0%BB%D0%B0%D0%B2%D1%8F%D0%BD%D1%81%D0%BA%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Светлая неделя в славянской традиции\" data-serp-pos=\"23\">Светлая неделя в славянской традиции</a> <span class=\"searchalttitle\">(перенаправление с <a href=\"/wiki/%D0%A1%D0%B2%D0%B5%D1%82%D0%BB%D0%B0%D1%8F_%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F_%D0%B2_%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Светлая неделя в народной традиции\">Светлая неделя в <span class=\"searchmatch\">народной</span> традиции</a>)</span>   </div> <div class=\"searchresult\">: Наука, 1990. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич</div>
<div class=\"mw-search-result-data\">66 КБ (4203 слова) - 12:11, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D1%8C%D0%B5_(%D0%BF%D1%80%D0%B0%D0%B7%D0%B4%D0%BD%D0%B8%D0%BA)\" title=\"Введенье (праздник)\" data-serp-pos=\"24\">Введенье (праздник)</a> <span class=\"searchalttitle\">(перенаправление с <a href=\"/wiki/%D0%92%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2_%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Введение в народной традиции\">Введение в <span class=\"searchmatch\">народной</span> традиции</a>)</span>   </div> <div class=\"searchresult\">&nbsp;— 668&nbsp;с.&nbsp;— (История в зеркале быта).&nbsp;— ISBN 5-210-01497-5. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">20 КБ (1173 слова) - 21:45, 11 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A0%D0%B0%D0%B4%D0%BE%D0%BD%D0%B8%D1%86%D0%BA%D0%B0%D1%8F_%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F\" title=\"Радоницкая неделя\" data-serp-pos=\"25\">Радоницкая неделя</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Словарь-справочник.&nbsp;— М.: Просвещение, 2002.&nbsp;— 334&nbsp;с.&nbsp;— ISBN 5-09-011134-0. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Максимов</div>
<div class=\"mw-search-result-data\">30 КБ (1838 слов) - 12:07, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%98%D0%B2%D0%B0%D0%BD_%D0%9A%D1%83%D0%BF%D0%B0%D0%BB%D0%B0\" title=\"Иван Купала\" data-serp-pos=\"26\">Иван Купала</a>  <span class=\"searchalttitle\">(категория Славянские <span class=\"searchmatch\">народные</span> праздники)</span>  </div> <div class=\"searchresult\">1915.&nbsp;— 51&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич</div>
<div class=\"mw-search-result-data\">94 КБ (6503 слова) - 03:22, 29 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A1%D0%B8%D0%BC%D0%BE%D0%BD%D0%BE%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Симонов день\" data-serp-pos=\"27\">Симонов день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Мельников-Печёрский</div>
<div class=\"mw-search-result-data\">14 КБ (812 слов) - 06:39, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9F%D0%B0%D1%81%D1%85%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%BA%D0%BE%D1%81%D1%82%D1%91%D1%80\" title=\"Пасхальный костёр\" data-serp-pos=\"28\">Пасхальный костёр</a>   <span class=\"searchalttitle\">(раздел «<a href=\"/wiki/%D0%9F%D0%B0%D1%81%D1%85%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%BA%D0%BE%D1%81%D1%82%D1%91%D1%80#.D0.9D.D0.B0.D1.80.D0.BE.D0.B4.D0.BD.D1.8B.D0.B5_.D0.BE.D0.B1.D1.8B.D1.87.D0.B0.D0.B8\" title=\"Пасхальный костёр\"><span class=\"searchmatch\">Народные</span> обычаи</a>»)</span> </div> <div class=\"searchresult\">Современный писатель, 1995.&nbsp;— Т.&nbsp;3.&nbsp;— 416&nbsp;с.&nbsp;— ISBN 5-265-03309-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с.</div>
<div class=\"mw-search-result-data\">9 КБ (603 слова) - 19:22, 17 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%95%D0%B3%D0%BE%D1%80%D0%B8%D0%B9_%D0%92%D0%B5%D1%88%D0%BD%D0%B8%D0%B9\" title=\"Егорий Вешний\" data-serp-pos=\"29\">Егорий Вешний</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\"> Ф., Христова Г. П..&nbsp;— Воронеж: Изд-во ВГУ, 2005.&nbsp;— 249&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Невский</div>
<div class=\"mw-search-result-data\">39 КБ (2543 слова) - 20:59, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9E%D0%B1%D1%80%D0%B5%D1%82%D0%B5%D0%BD%D1%8C%D0%B5\" title=\"Обретенье\" data-serp-pos=\"30\">Обретенье</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">на природу — М., 1995. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Русский <span class=\"searchmatch\">народный</span> календарь / Авт.-сост.</div>
<div class=\"mw-search-result-data\">12 КБ (679 слов) - 11:50, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%94%D0%B5%D0%BD%D1%8C_%D1%81%D0%B2%D1%8F%D1%82%D0%B8%D1%82%D0%B5%D0%BB%D1%8F_%D0%9D%D0%B8%D0%BA%D0%BE%D0%BB%D0%B0%D1%8F\" title=\"День святителя Николая\" data-serp-pos=\"31\">День святителя Николая</a>    </div> <div class=\"searchresult\">Европы. Зимние праздники.&nbsp;— М.: Наука, 1973.&nbsp;— С. 204–234. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995. Мадлевская Е. Л. Святочные игрища</div>
<div class=\"mw-search-result-data\">25 КБ (1469 слов) - 14:13, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A2%D0%B0%D1%82%D1%8C%D1%8F%D0%BD%D0%B8%D0%BD_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Татьянин день\" data-serp-pos=\"32\">Татьянин день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Шувалов: Татьянин день.&nbsp;— М.: АСТ, 1998.&nbsp;— ISBN 5-7632-0805-6. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">16 КБ (942 слова) - 20:04, 5 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%91%D0%B0%D0%B1%D1%8C%D0%B5_%D0%BB%D0%B5%D1%82%D0%BE\" title=\"Бабье лето\" data-serp-pos=\"33\">Бабье лето</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2-е изд.&nbsp;— СПб.&nbsp;: Типография М. О. Вольфа, 1880—1882.&nbsp;— Т.&nbsp;4. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Некрылова</div>
<div class=\"mw-search-result-data\">14 КБ (807 слов) - 07:07, 1 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%94%D0%B5%D0%B6%D0%B5%D0%BD%D1%8C\" title=\"Дежень\" data-serp-pos=\"34\">Дежень</a>    </div> <div class=\"searchresult\">А. Ларина.&nbsp;— М.: Прогресс, 1986.&nbsp;— Т. 1 (А — Д).&nbsp;— С. 494. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Терещенко</div>
<div class=\"mw-search-result-data\">7 КБ (273 слова) - 00:10, 3 марта 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A2%D1%80%D0%BE%D0%B8%D1%86%D1%8B%D0%BD_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Троицын день\" data-serp-pos=\"35\">Троицын день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">выхаванне, 2009.&nbsp;— 368&nbsp;с.&nbsp;— ISBN 978-985-6029-99-1. &nbsp;(белор.) <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Костомаров</div>
<div class=\"mw-search-result-data\">52 КБ (3079 слов) - 13:24, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9F%D0%B5%D1%82%D1%80%D0%BE%D0%B2%D1%81%D0%BA%D0%BE%D0%B5_%D0%B7%D0%B0%D0%B3%D0%BE%D0%B2%D0%B5%D0%BD%D1%8C%D0%B5\" title=\"Петровское заговенье\" data-serp-pos=\"36\">Петровское заговенье</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">&nbsp;— ISBN 5-235-01030-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Игры <span class=\"searchmatch\">народные</span>&nbsp;/ Морозов И. А.&nbsp;// Славянские</div>
<div class=\"mw-search-result-data\">11 КБ (657 слов) - 22:01, 30 ноября 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%94%D0%B5%D0%BD%D1%8C_%D0%A1%D0%B2%D1%8F%D1%82%D0%BE%D0%B3%D0%BE_%D0%A1%D0%B8%D0%BB%D1%8C%D0%B2%D0%B5%D1%81%D1%82%D1%80%D0%B0\" title=\"День Святого Сильвестра\" data-serp-pos=\"37\">День Святого Сильвестра</a>    </div> <div class=\"searchresult\">особенности праздника в проекте Календарь Праздников 2010 ↑ <span class=\"searchmatch\">Коринфский</span>, 1995   <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3</div>
<div class=\"mw-search-result-data\">9 КБ (471 слово) - 09:03, 4 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9D%D0%B0%D1%82%D0%B0%D0%BB%D1%8C%D1%8F_%D0%9E%D0%B2%D1%81%D1%8F%D0%BD%D0%B8%D1%86%D0%B0\" title=\"Наталья Овсяница\" data-serp-pos=\"38\">Наталья Овсяница</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Колесникова В. С. <span class=\"searchmatch\">Русь</span> православная. Праздники и обряды.&nbsp;— М.: Олма-пресс, 2005.&nbsp;— 606&nbsp;с.&nbsp;— ISBN 5-224-05162-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание</div>
<div class=\"mw-search-result-data\">8 КБ (379 слов) - 11:48, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9C%D0%B0%D1%82%D1%80%D1%91%D0%BD%D1%8B_%D0%B7%D0%B8%D0%BC%D0%BD%D0%B8%D0%B5\" title=\"Матрёны зимние\" data-serp-pos=\"39\">Матрёны зимние</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">выхаванне, 2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">10 КБ (544 слова) - 19:39, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A0%D1%83%D1%81%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D0%BD%D0%B5%D0%B4%D0%B5%D0%BB%D1%8F\" title=\"Русальная неделя\" data-serp-pos=\"40\">Русальная неделя</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\"> Ф., Христова Г. П..&nbsp;— Воронеж: Изд-во ВГУ, 2005.&nbsp;— 249&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Максимов</div>
<div class=\"mw-search-result-data\">32 КБ (1903 слова) - 20:27, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%91%D0%BB%D0%B0%D0%B3%D0%BE%D0%B2%D0%B5%D1%89%D0%B5%D0%BD%D1%8C%D0%B5%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Благовещеньев день\" data-serp-pos=\"41\">Благовещеньев день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Весенние праздники.&nbsp;— М.: Наука, 1977.&nbsp;— С.&nbsp;243–273.&nbsp;— 356&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Кулишић</div>
<div class=\"mw-search-result-data\">39 КБ (2466 слов) - 12:38, 20 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%92%D0%B0%D1%81%D0%B8%D0%BB%D1%8C%D0%B5%D0%B2_%D0%B2%D0%B5%D1%87%D0%B5%D1%80\" title=\"Васильев вечер\" data-serp-pos=\"42\">Васильев вечер</a>  <span class=\"searchalttitle\">(категория Славянские <span class=\"searchmatch\">народные</span> праздники)</span>  </div> <div class=\"searchresult\">Церковно-<span class=\"searchmatch\">народный</span> месяцеслов на Руси.&nbsp;— Записки Русского географического общества по отделению этнографии.&nbsp;— СПб., 1877.&nbsp;— Т.&nbsp;7. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> Русь</div>
<div class=\"mw-search-result-data\">33 КБ (2063 слова) - 10:04, 6 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A2%D1%80%D0%B8%D1%84%D0%BE%D0%BD%D0%BE%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Трифонов день\" data-serp-pos=\"43\">Трифонов день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">&nbsp;274–295.&nbsp;— 360&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич</div>
<div class=\"mw-search-result-data\">23 КБ (1467 слов) - 13:57, 30 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Михайлов день\" data-serp-pos=\"44\">Михайлов день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Миклухо-Маклая АН СССР.&nbsp;— М.: Наука, 1978.&nbsp;— С.&nbsp;200–222.&nbsp;— 296&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Месяцеслов</div>
<div class=\"mw-search-result-data\">15 КБ (872 слова) - 11:43, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A0%D0%B0%D0%B4%D0%BE%D0%BD%D0%B8%D1%86%D0%B0\" title=\"Радоница\" data-serp-pos=\"45\">Радоница</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">1996, с. 484  <span class=\"searchmatch\">Коринфский</span>, 1995, с. 192 ↑ Заклички. ННУ ↑ Нэй, 2012, с. 62–63   Агапкина Т. А. Мифопоэтические основы славянского <span class=\"searchmatch\">народного</span> календаря. Весенне-летний</div>
<div class=\"mw-search-result-data\">30 КБ (1824 слова) - 13:43, 4 декабря 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9A%D1%83%D0%B7%D1%8C%D0%BC%D0%B8%D0%BD%D0%BA%D0%B8_%D0%BE%D1%81%D0%B5%D0%BD%D0%BD%D0%B8%D0%B5\" title=\"Кузьминки осенние\" data-serp-pos=\"46\">Кузьминки осенние</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Институт славяноведения РАН, 2001.&nbsp;— 309&nbsp;с.&nbsp;— ISBN 5-7576-0095-0. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Максимов</div>
<div class=\"mw-search-result-data\">29 КБ (1886 слов) - 06:15, 29 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%94%D0%B5%D0%BD%D1%8C_%D0%9F%D0%B5%D1%82%D1%80%D0%B0_%D0%B8_%D0%A4%D0%B5%D0%B2%D1%80%D0%BE%D0%BD%D0%B8%D0%B8\" title=\"День Петра и Февронии\" data-serp-pos=\"47\">День Петра и Февронии</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2011. Архивировано из первоисточника 26 февраля 2012. ↑ <span class=\"searchmatch\">Коринфский</span>, 1901, с. 314 ↑ <span class=\"searchmatch\">Народная</span> культура Сибири, 1998, с. 96 ↑ Юдина, 2000, с. 309  Васілевіч</div>
<div class=\"mw-search-result-data\">24 КБ (1398 слов) - 21:59, 19 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A1%D0%B5%D1%80%D0%B3%D0%B5%D0%B9_%D0%9A%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%BD%D0%B8%D0%BA\" title=\"Сергей Капустник\" data-serp-pos=\"48\">Сергей Капустник</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">А.С.Суворина, 1901.&nbsp;— Т.&nbsp;1. Всенародный меяцеслов.&nbsp;— 691&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">15 КБ (922 слова) - 11:08, 20 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%94%D1%83%D1%85%D0%BE%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Духов день\" data-serp-pos=\"49\">Духов день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">21 января 2013. Архивировано из первоисточника 15 мая 2012. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Максимов</div>
<div class=\"mw-search-result-data\">31 КБ (1728 слов) - 17:18, 22 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9A%D1%80%D0%B5%D1%89%D0%B5%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D0%B2%D0%B5%D1%87%D0%B5%D1%80\" title=\"Крещенский вечер\" data-serp-pos=\"50\">Крещенский вечер</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Змора&nbsp;/ Е</div>
<div class=\"mw-search-result-data\">29 КБ (1985 слов) - 08:55, 14 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%95%D1%80%D0%B5%D0%BC%D0%B5%D0%B9_%D0%97%D0%B0%D0%BF%D1%80%D1%8F%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D0%BA\" title=\"Еремей Запрягальник\" data-serp-pos=\"51\">Еремей Запрягальник</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Весенние праздники.&nbsp;— М.: Наука, 1977.&nbsp;— С.&nbsp;274–295.&nbsp;— 360&nbsp;с. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Мельников-Печёрский</div>
<div class=\"mw-search-result-data\">23 КБ (1230 слов) - 06:11, 29 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%92%D0%BE%D0%B4%D0%BE%D0%BA%D1%80%D0%B5%D1%89%D0%B8\" title=\"Водокрещи\" data-serp-pos=\"52\">Водокрещи</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Т.&nbsp;Ф. Пухова, Г.&nbsp;П. Христова.&nbsp;— Воронеж: Изд-во ВГУ, 2005. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Наши</div>
<div class=\"mw-search-result-data\">23 КБ (1382 слова) - 20:35, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A0%D1%83%D1%81%D0%B0%D0%BB%D0%BA%D0%B0\" title=\"Русалка\" data-serp-pos=\"53\">Русалка</a>   <span class=\"searchalttitle\">(раздел «<a href=\"/wiki/%D0%A0%D1%83%D1%81%D0%B0%D0%BB%D0%BA%D0%B0#.D0.A0.D1.83.D1.81.D0.B0.D0.BB.D0.BA.D0.B0_.D0.B2_.D0.BD.D0.B0.D1.80.D0.BE.D0.B4.D0.BD.D0.BE.D0.BC_.D0.BA.D0.B0.D0.BB.D0.B5.D0.BD.D0.B4.D0.B0.D1.80.D0.B5\" title=\"Русалка\">Русалка в <span class=\"searchmatch\">народном</span> календаре</a>»)</span> </div> <div class=\"searchresult\">этнография и фольклор славянских народов.&nbsp;— М., 1978.&nbsp;— С. 210—226. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Левкиевская</div>
<div class=\"mw-search-result-data\">45 КБ (3121 слово) - 18:09, 5 марта 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%90%D0%BD%D1%82%D0%B8%D1%87%D0%BD%D0%BE%D1%81%D1%82%D1%8C\" title=\"Античность\" data-serp-pos=\"54\">Античность</a>    </div> <div class=\"searchresult\">впоследствии называлась Доридой, а оттуда часть их, вместе с этолийцами, через <span class=\"searchmatch\">Коринфский</span> залив переправлялась в Пелопоннес, до того времени занятый ахейцами и</div>
<div class=\"mw-search-result-data\">66 КБ (4337 слов) - 19:10, 2 марта 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%90%D1%84%D0%B0%D0%BD%D0%B0%D1%81%D0%B8%D0%B9_%D0%9B%D0%BE%D0%BC%D0%BE%D0%BD%D0%BE%D1%81\" title=\"Афанасий Ломонос\" data-serp-pos=\"55\">Афанасий Ломонос</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Европы. Зимние праздники.&nbsp;— М.: Наука, 1973.&nbsp;— С. 266–283. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">14 КБ (816 слов) - 20:29, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9C%D0%B0%D1%81%D0%BB%D0%B5%D0%BD%D0%B8%D1%86%D0%B0\" title=\"Масленица\" data-serp-pos=\"56\">Масленица</a>  <span class=\"searchalttitle\">(категория Славянские <span class=\"searchmatch\">народные</span> праздники)</span>  </div> <div class=\"searchresult\">выхаванне, 2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Кривчикова</div>
<div class=\"mw-search-result-data\">69 КБ (3977 слов) - 16:55, 8 марта 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9C%D1%8F%D1%81%D0%BE%D0%BF%D1%83%D1%81%D1%82%D0%BD%D0%B0%D1%8F_%D1%81%D1%83%D0%B1%D0%B1%D0%BE%D1%82%D0%B0\" title=\"Мясопустная суббота\" data-serp-pos=\"57\">Мясопустная суббота</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">12-05-2013 (1027&nbsp;дней)). &nbsp;(белор.) <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. <span class=\"searchmatch\">Народны</span> каляндар беларусаў, Реферат</div>
<div class=\"mw-search-result-data\">19 КБ (1065 слов) - 19:54, 4 марта 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9C%D0%B0%D1%80%D1%8C%D1%8F_%E2%80%94_%D0%B7%D0%B0%D0%B6%D0%B3%D0%B8_%D1%81%D0%BD%D0%B5%D0%B3%D0%B0\" title=\"Марья — зажги снега\" data-serp-pos=\"58\">Марья — зажги снега</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">выхаванне, 2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Левкиевская</div>
<div class=\"mw-search-result-data\">12 КБ (644 слова) - 10:07, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A4%D1%91%D0%B4%D0%BE%D1%80_%D0%A1%D1%82%D1%83%D0%B4%D0%B8%D1%82\" title=\"Фёдор Студит\" data-serp-pos=\"59\">Фёдор Студит</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Калинский И. Церковно-<span class=\"searchmatch\">народный</span> месяцеслов на Руси.&nbsp;— М.: Эксмо, 2008.&nbsp;— ISBN 978-5-699-27691-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца</div>
<div class=\"mw-search-result-data\">16 КБ (935 слов) - 13:25, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9F%D0%B0%D1%81%D1%85%D0%B0_%D0%B2_%D1%81%D0%BB%D0%B0%D0%B2%D1%8F%D0%BD%D1%81%D0%BA%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Пасха в славянской традиции\" data-serp-pos=\"60\">Пасха в славянской традиции</a> <span class=\"searchalttitle\">(перенаправление с <a href=\"/wiki/%D0%9F%D0%B0%D1%81%D1%85%D0%B0_%D0%B2_%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9_%D1%82%D1%80%D0%B0%D0%B4%D0%B8%D1%86%D0%B8%D0%B8\" title=\"Пасха в народной традиции\">Пасха в <span class=\"searchmatch\">народной</span> традиции</a>)</span>   </div> <div class=\"searchresult\">Котович.&nbsp;— Мн.: Беларусь, 2003.&nbsp;— 350&nbsp;с.&nbsp;— ISBN 985-01-0477-5. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Красавік</div>
<div class=\"mw-search-result-data\">92 КБ (5870 слов) - 16:29, 29 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9D%D0%B8%D0%BA%D0%B8%D1%82%D0%B0_%D0%92%D0%BE%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB\" title=\"Никита Водопол\" data-serp-pos=\"61\">Никита Водопол</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Благовещение&nbsp;/</div>
<div class=\"mw-search-result-data\">11 КБ (565 слов) - 22:17, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9C%D0%B0%D1%80%D1%8C%D0%B8_%D0%B4%D0%BE%D0%B1%D1%80%D1%8B%D0%B9_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Марьи добрый день\" data-serp-pos=\"62\">Марьи добрый день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Калинский И. Церковно-<span class=\"searchmatch\">народный</span> месяцеслов на Руси.&nbsp;— М.: Эксмо, 2008.&nbsp;— ISBN 978-5-699-27691-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца</div>
<div class=\"mw-search-result-data\">12 КБ (579 слов) - 16:13, 11 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%92%D0%B0%D1%80%D0%B2%D0%B0%D1%80%D0%B8%D0%BD_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Варварин день\" data-serp-pos=\"63\">Варварин день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">23 октября. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Макаренко, А. А. Сибирский <span class=\"searchmatch\">народный</span> календарь.&nbsp;—</div>
<div class=\"mw-search-result-data\">31 КБ (1917 слов) - 00:17, 20 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%90%D0%B3%D1%80%D0%B0%D1%84%D0%B5%D0%BD%D0%B0_%D0%9A%D1%83%D0%BF%D0%B0%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D0%B0\" title=\"Аграфена Купальница\" data-serp-pos=\"64\">Аграфена Купальница</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Колесникова В. <span class=\"searchmatch\">Русь</span> православная. Праздники и обряды.&nbsp;— М.: Олма-Пресс, 2005.&nbsp;— 606&nbsp;с.&nbsp;— ISBN 5-224-05162-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск:</div>
<div class=\"mw-search-result-data\">24 КБ (1476 слов) - 20:28, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A4%D1%80%D0%BE%D0%BB_%D0%B8_%D0%9B%D0%B0%D0%B2%D1%91%D1%80_%E2%80%94_%D0%BB%D0%BE%D1%88%D0%B0%D0%B4%D0%BD%D0%B8%D0%BA%D0%B8\" title=\"Фрол и Лавёр — лошадники\" data-serp-pos=\"65\">Фрол и Лавёр — лошадники</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">(Сказка) — Я (Ящерица).&nbsp;— С.&nbsp;399–401.&nbsp;— ISBN 978-5-7133-1380-7. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">15 КБ (850 слов) - 13:26, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%93%D1%80%D0%B5%D0%BA%D0%B8\" title=\"Греки\" data-serp-pos=\"66\">Греки</a>    </div> <div class=\"searchresult\">алфавитов&nbsp;— ионийский (Иония), афинский (Аттика), аргосский (Арголида), <span class=\"searchmatch\">коринфский</span>. После того, как македонский клан лагидов стал династией правителей Египта</div>
<div class=\"mw-search-result-data\">69 КБ (3756 слов) - 22:11, 19 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9A%D0%B0%D0%B7%D0%B0%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%BE%D1%81%D0%B5%D0%BD%D0%BD%D1%8F%D1%8F\" title=\"Казанская осенняя\" data-serp-pos=\"67\">Казанская осенняя</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Крестьянское</div>
<div class=\"mw-search-result-data\">16 КБ (913 слов) - 09:47, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9E%D0%BD%D0%B8%D1%81%D0%B8%D0%BC_%D0%9E%D0%B2%D1%87%D0%B0%D1%80\" title=\"Онисим Овчар\" data-serp-pos=\"68\">Онисим Овчар</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">СПб.: Терра — Азбука, 1995.&nbsp;— 176&nbsp;с.&nbsp;— ISBN 5-300-00114-7. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">10 КБ (550 слов) - 11:50, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%90%D0%B3%D0%B0%D1%84%D1%8C%D1%8F_%D0%9A%D0%BE%D1%80%D0%BE%D0%B2%D0%BD%D0%B8%D1%86%D0%B0\" title=\"Агафья Коровница\" data-serp-pos=\"69\">Агафья Коровница</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">обряды.&nbsp;— М.: Олма-Пресс, 2005.&nbsp;— 606&nbsp;с.&nbsp;— ISBN 5-224-05162-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">19 КБ (1186 слов) - 20:27, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%98%D0%B2%D0%B0%D0%BD_%E2%80%94_%D0%9C%D0%B5%D0%B4%D0%B2%D1%8F%D0%BD%D1%8B%D0%B5_%D1%80%D0%BE%D1%81%D1%8B\" title=\"Иван — Медвяные росы\" data-serp-pos=\"70\">Иван — Медвяные росы</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">13 КБ (645 слов) - 21:15, 21 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%92%D0%BE%D0%BB%D0%BE%D1%87%D0%B5%D0%B1%D0%BD%D1%8B%D0%B9_%D0%BE%D0%B1%D1%80%D1%8F%D0%B4\" title=\"Волочебный обряд\" data-serp-pos=\"71\">Волочебный обряд</a>    </div> <div class=\"searchresult\">Упоряд. В. В. Яременко.&nbsp;— К.: Либідь, 1993.&nbsp;— Т.&nbsp;1. &nbsp;(укр.) <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Котеля</div>
<div class=\"mw-search-result-data\">33 КБ (1870 слов) - 19:51, 13 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%BE_%D1%87%D1%83%D0%B4%D0%BE\" title=\"Михайлово чудо\" data-serp-pos=\"72\">Михайлово чудо</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Колесникова В. С. <span class=\"searchmatch\">Русь</span> православная. Праздники и обряды.&nbsp;— М.: Олма-пресс, 2005.&nbsp;— 606&nbsp;с.&nbsp;— ISBN 5-224-05162-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание</div>
<div class=\"mw-search-result-data\">16 КБ (949 слов) - 11:44, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A1%D0%B5%D0%BC%D1%91%D0%BD_%D0%9B%D0%B5%D1%82%D0%BE%D0%BF%D1%80%D0%BE%D0%B2%D0%BE%D0%B4%D0%B5%D1%86\" title=\"Семён Летопроводец\" data-serp-pos=\"73\">Семён Летопроводец</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Лаврентьева</div>
<div class=\"mw-search-result-data\">37 КБ (2337 слов) - 06:51, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9F%D0%B0%D1%80%D0%B0%D1%81%D0%BA%D0%B5%D0%B2%D1%8B_%D0%9B%D1%8C%D0%BD%D1%8F%D0%BD%D0%B8%D1%86%D1%8B\" title=\"Параскевы Льняницы\" data-serp-pos=\"74\">Параскевы Льняницы</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Лаврентьева</div>
<div class=\"mw-search-result-data\">15 КБ (928 слов) - 17:56, 21 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9B%D0%B5%D1%82%D0%BD%D0%B8%D0%B5_%D0%9A%D1%83%D0%B7%D1%8C%D0%BC%D0%B8%D0%BD%D0%BA%D0%B8\" title=\"Летние Кузьминки\" data-serp-pos=\"75\">Летние Кузьминки</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Месяцеслов</div>
<div class=\"mw-search-result-data\">13 КБ (750 слов) - 10:01, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%90%D0%BD%D0%B4%D1%80%D0%B5%D0%B5%D0%B2_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Андреев день\" data-serp-pos=\"76\">Андреев день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">С.&nbsp;157–175.&nbsp;— 242&nbsp;с.&nbsp;— (Диалог).&nbsp;— ISBN 978-5-89647-262-9. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Мясников</div>
<div class=\"mw-search-result-data\">19 КБ (1200 слов) - 20:28, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9A%D1%83%D0%B4%D0%B5%D0%BB%D0%B8%D1%86%D0%B0\" title=\"Куделица\" data-serp-pos=\"77\">Куделица</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">Калинский И. Церковно-<span class=\"searchmatch\">народный</span> месяцеслов на Руси.&nbsp;— М.: Терра, 1997.&nbsp;— 301&nbsp;с.&nbsp;— ISBN 5-300-01265-3. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца</div>
<div class=\"mw-search-result-data\">15 КБ (900 слов) - 18:00, 21 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A4%D1%91%D0%BA%D0%BB%D0%B0_%D0%97%D0%B0%D1%80%D0%B5%D0%B2%D0%BD%D0%B8%D1%86%D0%B0\" title=\"Фёкла Заревница\" data-serp-pos=\"78\">Фёкла Заревница</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Овин&nbsp;/ Левкиевская</div>
<div class=\"mw-search-result-data\">26 КБ (1710 слов) - 10:18, 5 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%93%D0%B0%D0%B2%D1%80%D0%B8%D0%BB%D0%B0_%D0%9B%D0%B5%D1%82%D0%BD%D0%B8%D0%B9\" title=\"Гаврила Летний\" data-serp-pos=\"79\">Гаврила Летний</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">&nbsp;— ISBN 5-7133-0982-7. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Русский <span class=\"searchmatch\">народный</span> календарь / Авт.-сост</div>
<div class=\"mw-search-result-data\">12 КБ (698 слов) - 20:38, 18 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%90%D1%80%D0%B7%D0%B0%D0%BC%D0%B0%D1%81%D1%81%D0%BA%D0%B8%D0%B9_%D1%80%D0%B0%D0%B9%D0%BE%D0%BD\" title=\"Арзамасский район\" data-serp-pos=\"80\">Арзамасский район</a>    </div> <div class=\"searchresult\">российский педагог, ученый, методист начальной школы, деятель <span class=\"searchmatch\">народного</span> образования. <span class=\"searchmatch\">Коринфский</span> Михаил Петрович&nbsp;(1788 - 22.06.1851) — родился в Арзамасе,</div>
<div class=\"mw-search-result-data\">79 КБ (2224 слова) - 01:26, 22 октября 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9A%D0%B0%D1%82%D0%B5%D1%80%D0%B8%D0%BD%D0%B0_%D0%A1%D0%B0%D0%BD%D0%BD%D0%B8%D1%86%D0%B0\" title=\"Катерина Санница\" data-serp-pos=\"81\">Катерина Санница</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Некрылова</div>
<div class=\"mw-search-result-data\">21 КБ (1273 слова) - 09:49, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A5%D0%BC%D0%B5%D0%BB%D1%8C%D0%BD%D0%B8%D1%86%D0%BA%D0%B8%D0%B9,_%D0%91%D0%BE%D0%B3%D0%B4%D0%B0%D0%BD_%D0%9C%D0%B8%D1%85%D0%B0%D0%B9%D0%BB%D0%BE%D0%B2%D0%B8%D1%87\" title=\"Хмельницкий, Богдан Михайлович\" data-serp-pos=\"82\">Хмельницкий, Богдан Михайлович</a>    </div> <div class=\"searchresult\">принятии Войска Запорожского под высокую государеву руку». Митрополит <span class=\"searchmatch\">Коринфский</span> Иоасаф препоясал гетмана мечом, освящённым на Гробе Господнем в Иерусалиме</div>
<div class=\"mw-search-result-data\">128 КБ (8668 слов) - 12:18, 27 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%98%D0%B2%D0%B0%D0%BD%D0%BE%D0%B2%D1%81%D0%BA%D0%B8%D0%B5_%D1%82%D1%80%D0%B0%D0%B2%D1%8B\" title=\"Ивановские травы\" data-serp-pos=\"83\">Ивановские травы</a>    </div> <div class=\"searchresult\">&nbsp;— ISBN 5-7133-0704-2. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Русская <span class=\"searchmatch\">народная</span> поэзия. Обрядовая поэзия</div>
<div class=\"mw-search-result-data\">20 КБ (1501 слово) - 20:01, 13 декабря 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A1%D0%BA%D0%B0%D0%B7%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BE_%D0%BF%D0%BE%D0%B4%D0%B2%D0%B8%D0%B3%D0%B0%D1%85_%D0%A4%D1%91%D0%B4%D0%BE%D1%80%D0%B0_%D0%A2%D0%B8%D1%80%D0%B8%D0%BD%D0%B8%D0%BD%D0%B0\" title=\"Сказание о подвигах Фёдора Тиринина\" data-serp-pos=\"84\">Сказание о подвигах Фёдора Тиринина</a>    </div> <div class=\"searchresult\">&nbsp;— 624&nbsp;с.&nbsp;— (Российские Пропилеи).&nbsp;— ISBN 978-5-8243-1279-9. <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995.&nbsp;— 656&nbsp;с.&nbsp;— ISBN 5-88590-309-3. Памятники</div>
<div class=\"mw-search-result-data\">20 КБ (1566 слов) - 15:23, 20 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%95%D0%BB%D0%B5%D0%BD%D0%B8%D0%BD_%D0%B4%D0%B5%D0%BD%D1%8C\" title=\"Еленин день\" data-serp-pos=\"85\">Еленин день</a>  <span class=\"searchalttitle\">(категория <span class=\"searchmatch\">Народный</span> календарь восточных славян)</span>  </div> <div class=\"searchresult\">2010.&nbsp;— 592&nbsp;с.&nbsp;— 3000 экз.&nbsp;— ISBN 978-985-471-335-9. Коринфский А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— М.: Издание книгопродавца М. В. Клюкина, 1901.&nbsp;— 723&nbsp;с. Максимов</div>
<div class=\"mw-search-result-data\">16 КБ (963 слова) - 20:59, 21 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A8%D0%B8%D1%80%D1%8F%D0%B5%D0%B2%D0%B5%D1%86,_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80\" title=\"Ширяевец, Александр\" data-serp-pos=\"86\">Ширяевец, Александр</a>    </div> <div class=\"searchresult\">&nbsp;— (Литографир. издание).  Александр Ширяевец на сайте «А в сердце светит <span class=\"searchmatch\">Русь</span>» Е. Койнова. «В песнях — соловей…»[1] Поэт Александр Ширяевец «Наш Современник»</div>
<div class=\"mw-search-result-data\">20 КБ (1349 слов) - 19:07, 29 октября 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A2%D1%80%D0%BE%D1%8F%D0%BD%D1%81%D0%BA%D0%B0%D1%8F_%D0%B2%D0%BE%D0%B9%D0%BD%D0%B0\" title=\"Троянская война\" data-serp-pos=\"87\">Троянская война</a>    </div> <div class=\"searchresult\">столетий второго тысячелетия до&nbsp;н.&nbsp;э.    Катастрофа бронзового века   ↑ Грани. <span class=\"searchmatch\">Ру</span> // Культура / Учёные установили дату возвращения Одиссея на Итаку. Архивировано</div>
<div class=\"mw-search-result-data\">55 КБ (3496 слов) - 10:22, 8 марта 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%A0%D1%83%D1%81%D1%81%D0%BA%D0%B8%D0%B9_%D0%BC%D0%B5%D1%81%D1%8F%D1%86%D0%B5%D1%81%D0%BB%D0%BE%D0%B2\" title=\"Русский месяцеслов\" data-serp-pos=\"88\">Русский месяцеслов</a> <span class=\"searchalttitle\">(перенаправление с <a href=\"/wiki/%D0%9C%D0%B5%D1%81%D1%8F%D1%86%D0%B5%D1%81%D0%BB%D0%BE%D0%B2_%D0%BD%D0%B0%D1%80%D0%BE%D0%B4%D0%BD%D1%8B%D0%B9\" title=\"Месяцеслов народный\">Месяцеслов <span class=\"searchmatch\">народный</span></a>)</span>   </div> <div class=\"searchresult\">нашого народу.&nbsp;— К.: АВПТ «Оберіг», 1993.&nbsp;— 507&nbsp;с. &nbsp;(укр.) <span class=\"searchmatch\">Коринфский</span> А. А. <span class=\"searchmatch\">Народная</span> <span class=\"searchmatch\">Русь</span>.&nbsp;— Смоленск: Русич, 1995. Некрылова А. Ф. Круглый год.&nbsp;— М.:</div>
<div class=\"mw-search-result-data\">155 КБ (480 слов) - 16:49, 17 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%98%D0%BA%D0%BE%D0%BD%D0%BE%D1%81%D1%82%D0%B0%D1%81\" title=\"Иконостас\" data-serp-pos=\"89\">Иконостас</a>    </div> <div class=\"searchresult\">Здесь также присутствовала либо ориентация на Византию, либо на Древнюю <span class=\"searchmatch\">Русь</span>. Но понимание как формы, так и содержания древних памятников стало гораздо</div>
<div class=\"mw-search-result-data\">124 КБ (8120 слов) - 17:00, 19 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%94%D0%B2%D0%BE%D1%80%D0%B5%D1%86_%D0%BA%D1%83%D0%BB%D1%8C%D1%82%D1%83%D1%80%D1%8B_%D0%B8%D0%BC%D0%B5%D0%BD%D0%B8_%D0%92._%D0%98._%D0%9B%D0%B5%D0%BD%D0%B8%D0%BD%D0%B0_(%D0%9F%D0%B5%D1%80%D0%BC%D1%8C)\" title=\"Дворец культуры имени В. И. Ленина (Пермь)\" data-serp-pos=\"90\">Дворец культуры имени В. И. Ленина (Пермь)</a>    </div> <div class=\"searchresult\">контрольного пакета акций ОАО «Мотовилихинские заводы»&nbsp;— группа компаний ФД «<span class=\"searchmatch\">Русь</span>» продали Дворец культуры им. В.&nbsp;И.&nbsp;Ленина Пермскому епархиальному управлению</div>
<div class=\"mw-search-result-data\">23 КБ (743 слова) - 19:24, 19 января 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%91%D0%B0%D0%BB%D0%BA%D0%B0%D0%BD%D1%81%D0%BA%D0%B8%D0%B9_%D1%82%D0%B5%D0%B0%D1%82%D1%80_%D0%B2%D0%BE%D0%B5%D0%BD%D0%BD%D1%8B%D1%85_%D0%B4%D0%B5%D0%B9%D1%81%D1%82%D0%B2%D0%B8%D0%B9_%D0%9F%D0%B5%D1%80%D0%B2%D0%BE%D0%B9_%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%BE%D0%B9_%D0%B2%D0%BE%D0%B9%D0%BD%D1%8B\" title=\"Балканский театр военных действий Первой мировой войны\" data-serp-pos=\"91\">Балканский театр военных действий Первой мировой войны</a>    </div> <div class=\"searchresult\">Одновременно с этим французские и итальянские войска заняли Фессалию, <span class=\"searchmatch\">Коринфский</span> перешеек, Янину и Эпир с целью пресечь всяческие выступления греческих</div>
<div class=\"mw-search-result-data\">295 КБ (18&nbsp;355 слов) - 19:27, 25 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%90%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%B0_%D0%9F%D0%B0%D1%80%D0%B8%D0%B6%D0%B0_%D0%B2_%D1%8D%D0%BF%D0%BE%D1%85%D1%83_%D0%B0%D0%B1%D1%81%D0%BE%D0%BB%D1%8E%D1%82%D0%B8%D0%B7%D0%BC%D0%B0\" title=\"Архитектура Парижа в эпоху абсолютизма\" data-serp-pos=\"92\">Архитектура Парижа в эпоху абсолютизма</a>    </div> <div class=\"searchresult\">ограничили просторную площадь Согласия. Неоклассический восьмиколонный <span class=\"searchmatch\">коринфский</span> портик церкви Мадлен работы архитектора Пьера-Александра Виньона (начало</div>
<div class=\"mw-search-result-data\">240 КБ (15&nbsp;440 слов) - 17:51, 25 февраля 2016</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9F%D0%BE%D0%B2%D0%B0%D1%80%D1%81%D0%BA%D0%B0%D1%8F_%D1%83%D0%BB%D0%B8%D1%86%D0%B0\" title=\"Поварская улица\" data-serp-pos=\"93\">Поварская улица</a>    </div> <div class=\"searchresult\">2010. Архивировано из первоисточника 21 августа 2011. ↑ Чагин Г. \"…Москва и <span class=\"searchmatch\">Русь</span> одно и то же…\".  aksakov.ouc.ru. Проверено 9 июня 2010. Архивировано из первоисточника</div>
<div class=\"mw-search-result-data\">344 КБ (19&nbsp;896 слов) - 07:48, 14 декабря 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%9E%D1%81%D0%BE%D0%B1%D0%BD%D1%8F%D0%BA_%D0%A0%D1%83%D0%BC%D1%8F%D0%BD%D1%86%D0%B5%D0%B2%D0%B0\" title=\"Особняк Румянцева\" data-serp-pos=\"94\">Особняк Румянцева</a>    </div> <div class=\"searchresult\">портиком, установленным на высокий цоколь. Колонны портика с капителями <span class=\"searchmatch\">коринфского</span> ордера подчёркивали его монументальность. В тимпане фронтона портика</div>
<div class=\"mw-search-result-data\">38 КБ (2502 слова) - 23:06, 17 ноября 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%90%D1%80%D1%85%D0%B8%D1%82%D0%B5%D0%BA%D1%82%D1%83%D1%80%D0%B0_%D0%9A%D0%BE%D0%BB%D0%BE%D0%BC%D0%BD%D1%8B\" title=\"Архитектура Коломны\" data-serp-pos=\"95\">Архитектура Коломны</a>    </div> <div class=\"searchresult\">Больницы на Красной (б. Репинской) улице, незавершённое (не выполнены <span class=\"searchmatch\">коринфские</span> капители колонн) и переходящее в ампир своей растянутостью». Культовые</div>
<div class=\"mw-search-result-data\">77 КБ (2410 слов) - 16:32, 2 октября 2015</div></li>
<li><div class=\"mw-search-result-heading\"><a href=\"/wiki/%D0%AE%D0%B2%D0%B5%D0%BD%D1%82%D0%B0_(%D1%82%D0%B5%D0%B0%D1%82%D1%80)\" title=\"Ювента (театр)\" data-serp-pos=\"96\">Ювента (театр)</a>    </div> <div class=\"searchresult\">соединялось с главным корпусом переходом. Зал украшен колоннами и пилястрами <span class=\"searchmatch\">коринфского</span> ордера, облицован искусственным мрамором. Именно П.&nbsp;С.&nbsp;Плавов изменил</div>
<div class=\"mw-search-result-data\">44 КБ (2542 слова) - 19:07, 25 июня 2015</div>";

//$t = addslashes($t);
//$xml = simplexml_load_string($t);
//$search_results = $xml->xpath('div[@class=.mw-search-results]');

$t = preg_match_all('~<a[^>]+>(.*?)</a>~u', $t, $found);
foreach($found[1] as $p) echo showarray($p);
//showarray($found[1]);


/*
foreach ($xml->page as $page) {


	.mw-search-results > li:nth-child(1) > div:nth-child(1) > a:nth-child(1)

	//showarray($page);
	$title = $page->title;
	$t  = $page->revision->text;

	$title  = str_replace('ТСД/', '', $title);
	$t = preg_replace("/\n/u", "##BR##", $t);


	//echo $pb[1];
	//showarray($nazvanie_DO); //[1].' # '$pb[1].' | '.$pb[1]

	// формат вывода:  # Ссылка на статью || Название_в_ДО # диапазон книги|диапазон скана (или просто номер первой страницы скана)
	//$list[] = '# '.$title.' || '.$nazvanie_DO[1].' # '.$pb[1].' | '.$ps[1];
	//$list[] = $title.'~'.$nazvanie_DO[1].'~'.$pb[1].'~'.$ps[1];
	$list[] = array($title, $found[1].$found[2].$found[3].$found[4].$found[5]);
	//showarray($found);

	//$list[] = array($title, $nazvanie_DO[1], $pb[1],$ps[1]);
	//fsave_csv($fout, $list, '~')
	//implode("~", $array);
}
	showarray($list);

// запись файла csv
//fsave_csv($fout, $list, '~')
//file_put_contents($fout, implode ('\r\n',$list);
//fsave($fout, implode ("\n",$list));





*/

?>